# Generated by Django 2.1.1 on 2019-01-19 23:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(default='', error_messages={'blank': 'El campo no puede estar vacio', 'null': 'No se admiten valores nulos', 'unique': 'Ya existe ese menu'}, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre no puede estar vacios', regex='^[A-Za-záéíóúáéíóúÁÉÍÓÚ]+$')])),
            ],
        ),
        migrations.CreateModel(
            name='NodoMenu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('etiqueta', models.CharField(error_messages={'max_length': 'La longitud maxima es de %(limit_value)d caracteres (tiene %(show_value)d)'}, max_length=60)),
                ('orden', models.PositiveIntegerField(error_messages={'min_value': 'No se puede mover a un orden menor a 0'}, validators=[django.core.validators.MinValueValidator(0)])),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametros.Menu')),
                ('nodo_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subnodomenu', to='parametros.NodoMenu')),
            ],
        ),
    ]
