# Generated by Django 2.1.1 on 2018-09-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='nombre',
            field=models.TextField(default=''),
        ),
    ]
